### ISSUE TITLE
How to get debug working with create-react-app [question]

### ISSUE THREAD

**Issue by zg-trinac** [nithinpeter/jest-run-it#22]
Question- how do you get debug working with create-react-app repos?

I've got the `Run` command working by setting the **Jest Run It: Jest Path** to `node_modules/.bin/react-scripts test`, but this only works for Run, not Debug.

Debug outputs this error:

```
Debugger listening on ws://127.0.0.1:52155/67198ca8-c598-45d0-9f63-25dd372716a6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module '/Users/cathrync/gitlab/my-project/node_modules/.bin/react-scripts test'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by zg-trinac** [comment]
Without `test` in the Jest Path the error is:

```
Debugger listening on ws://127.0.0.1:52348/c2c7985a-f3c6-4b78-a120-6caffff48cc6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Unknown script "/Users/cathrync/gitlab/my-project/src/components/Codes/__tests__/Codes.test.js".
Perhaps you need to update react-scripts?
See: https://facebook.github.io/create-react-app/docs/updating-to-new-releases
Waiting for the debugger to disconnect...
```

**Comment by nithinpeter** [comment]
Hmm – not sure if there is a better way, but setting the Jest Path in the config to `./node_modules/react-scripts/scripts/test.js` did the trick for me.
